name: Update storybook site
on:
    push:
        paths:
            - 'apps/docs/**'
            - '.changeset/**'
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build-and-deploy:
        name: 'Build and deploy doc site'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install Dependencies
              run: npm install

            - name: Build docs
              run: npm run build-docs

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: apps/docs/storybook-static # The folder that the build-storybook script generates files.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
                  TARGET_FOLDER: docs # The folder that we serve our Storybook files from